### ISSUE TITLE
Popup "Xbox CreateDevice did not call SetRenderTarget In Direct3D_CreateDevice_End"

### ISSUE THREAD

**Issue by jeltaqq** [Cxbx-Reloaded/Cxbx-Reloaded#1733]
LOG_TEST_CASE: Xbox CreateDevice did not call SetRenderTarget
In Direct3D_CreateDevice_End (C:\projects\cxbx-reloaded\src\core\hle\D3D8\Direct3D9\Direct3D9.cpp line 2595)

Plus
Received Fatal Message:
Unable to determine default Xbox backbuffer

Titles:
- Aggressive Inline
- ATV: Quad Power Racing 2
- Battle Engine Aquila
- Kelly Slater's Pro Surfer

**Comment by RadWolfie** [comment]
@LukeUsher mentioned to me about this popup message only occur when title is missing important symbol detection.

**Comment by literalmente-game** [comment]
Added these to the list:

- Brute Force
- Call of Cthulu: Dark Corners of the Earth
- Deathrow
- Lord of the Rings Fellowship of the Rings
- Miami Vice
- Murakumo Renegade Mech Pursuit
- Spartan - Total Warrior
- Sensable Soccer 2006

**Comment by ObiKKa** [comment]
There are two small PRs (#1888 & #1889), which may make it worthwhile retesting any to all of the above listed games and demos (seen in various posts). See what happens with those CreateDevice failed popups or not.

**Comment by jeltaqq** [comment]
Fixed by PR #2022. Thank you fixing.

**Comment by ObiKKa** [comment]
This game (Also mentioned in literalmente's comment above) still exhibits this message. So it's not fully resolved then.

- [Call of Cthulhu: Dark Corners of the Earth](https://github.com/Cxbx-Reloaded/game-compatibility/issues/1073#issue-781470650)
