### ISSUE TITLE
Burnout 1 Crash

### ISSUE THREAD

**Issue by UlsterRose** [Cxbx-Reloaded/Cxbx-Reloaded#69]
This is with Cxbx-Reloaded ea95cfc (25 Dec 2016.) I'm able to go through all the menus and even choose a car and track before the crash, although there are quite a lot of graphical issues, and there's no sound.

Here's the last bit of the log when it crashes:

EmuMain (0x1B98): Recieved Exception (Code := 0xC0000005)

 EIP := 0x6CA17EA0 EFL := 0x00010282
 EAX := 0x83BDFD6D EBX := 0x0AD421FC ECX := 0x6C9F1070 EDX := 0x7FFFFFFF
 ESI := 0x00000000 EDI := 0x00000004 ESP := 0x0E45FB34 EBP := 0x0E45FB38
 CR2 := 0x00000000

![cxbx_burnoutcrash](https://cloud.githubusercontent.com/assets/8225831/21485978/e3ba1694-cba3-11e6-94fe-39b6c04c0abb.png)

The reason I'm reporting this is because of how similar it is to #63 (at least to a black-box tester of Cxbx like me.)

**Comment by PatrickvL** [comment]
Thanks for reporting this - yet another title to test with!

**Comment by DisorderIy** [comment]
Not sure if this is of much use, but whenever I'm in the car select, I get a consistent spam of this in the console:

[0x2098] EmuWarn: Trying fixed or recompiled programmable pipeline pixel shader!
[0x2098] EmuWarn: We're lying about setting a pixel shader!
[0x2098] EmuWarn: Not setting palette
[0x2098] EmuWarn: Not setting palette
[0x2098] EmuWarn: Not setting palette
[0x2098] EmuWarn: Not setting palette
[0x2098] EmuWarn: Not setting palette
[0x2098] EmuWarn: EmuX86_Write32(0x0000042C, 0x00000001) [Unknown address]
[0x2098] EmuWarn: EmuX86_Write32(0x00000430, 0x00000000) [Unknown address]
[0x2098] EmuWarn: EmuX86_Write32(0x00000434, 0x001A6848) [Unknown address]
[0x2098] EmuWarn: Trying fixed or recompiled programmable pipeline pixel shader!
[0x2098] EmuWarn: We're lying about setting a pixel shader!
[0x2098] EmuWarn: EmuX86_Write32(0x0000042C, 0x00000001) [Unknown address]
[0x2098] EmuWarn: EmuX86_Write32(0x00000430, 0x00000000) [Unknown address]
[0x2098] EmuWarn: EmuX86_Write32(0x00000434, 0x001A6848) [Unknown address]
[0x2098] EmuWarn: Trying fixed or recompiled programmable pipeline pixel shader!
[0x2098] EmuWarn: We're lying about setting a pixel shader!
[0x2098] EmuWarn: EmuX86_Write32(0x0000042C, 0x00000001) [Unknown address]
[0x2098] EmuWarn: EmuX86_Write32(0x00000430, 0x00000000) [Unknown address]
[0x2098] EmuWarn: EmuX86_Write32(0x00000434, 0x001A6938) [Unknown address]
[0x2098] EmuWarn: Trying fixed or recompiled programmable pipeline pixel shader!
[0x2098] EmuWarn: We're lying about setting a pixel shader!
[0x2098] EmuWarn: EmuX86_Write32(0x0000042C, 0x00000001) [Unknown address]
[0x2098] EmuWarn: EmuX86_Write32(0x00000430, 0x00000000) [Unknown address]
[0x2098] EmuWarn: EmuX86_Write32(0x00000434, 0x001A6848) [Unknown address]
[0x2098] EmuWarn: Trying fixed or recompiled programmable pipeline pixel shader!
[0x2098] EmuWarn: We're lying about setting a pixel shader!
[0x2098] EmuWarn: EmuX86_Write32(0x0000042C, 0x00000001) [Unknown address]
[0x2098] EmuWarn: EmuX86_Write32(0x00000430, 0x00000000) [Unknown address]
[0x2098] EmuWarn: EmuX86_Write32(0x00000434, 0x001A6848) [Unknown address]
[0x2098] EmuWarn: Trying fixed or recompiled programmable pipeline pixel shader!
[0x2098] EmuWarn: We're lying about setting a pixel shader!
[0x2098] EmuWarn: EmuX86_Write32(0x0000042C, 0x00000001) [Unknown address]
[0x2098] EmuWarn: EmuX86_Write32(0x00000430, 0x00000000) [Unknown address]
[0x2098] EmuWarn: EmuX86_Write32(0x00000434, 0x001A6938) [Unknown address]

This goes away when I go back to the main menu.

**Comment by LukeUsher** [comment]
The EmuX86 lines imply we are missing some HLE patches for this XDK, this could possibly 'fix itself' as we improve the HLE Database/function detection

**Comment by jarupxx** [comment]
I checked xdk 4361 and added a missing symbol.
The EmuX 86 line has disappeared, but it crashes as well.

If interested, we can test it here.
https://github.com/jarupxx/Cxbx-Reloaded/commits/fnc-3

**Comment by LukeUsher** [comment]
Is this crash dump (EIP := 0x6CA17EA0, etc) identical to the one documented in this issue, or did the details change after adding the missing symbol?

**Comment by jarupxx** [comment]
Crash dumps are different from documented. The value seems to change every time it is executed.
```
[0x24AC] EmuMain: Recieved Exception (Code := 0xC0000005)

 EIP := 0x66E47EA0 EFL := 0x00010202
 EAX := 0x63311791 EBX := 0x00000000 ECX := 0x66E47E90 EDX := 0x66E21070
 ESI := 0x0F0AFACC EDI := 0x0F0AFB74 ESP := 0x0F0AFAB4 EBP := 0x0F0AFAB8
 CR2 := 0x00000000
```
Not sure if this is useful, but before the crash Microsoft Visual C ++ Runtime Library Debug Error! Appears.
If I Ignore this error, causes Line: 1175 similar Debug Error!
```
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Error!

Program: D:\Git\Cxbx-Reloaded-fnc-3\build\win32\Debug\CxbxKrnl.dll
Module: D:\Git\Cxbx-Reloaded-fnc-3\build\win32\Debug\CxbxKrnl.dll
File: d:\git\cxbx-reloaded-fnc-3\src\cxbxkrnl\emud3d8.cpp
Line: 1163

Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention.

(Press Retry to debug the application)

---------------------------
Abort (A) Retry (R) Ignore (I)
---------------------------
```
https://github.com/jarupxx/Cxbx-Reloaded/blob/fnc-3/src/CxbxKrnl/EmuD3D8.cpp#L1163

**Comment by DisorderIy** [comment]
Oddly enough, Burnout 3 crashes on startup with a very similar error:

```
[0x141C] EmuMain: Recieved Exception (Code := 0xC0000005)

 EIP := 0x00351A3A EFL := 0x00010286
 EAX := 0x80000000 EBX := 0x00080000 ECX := 0x00000000 EDX := 0x00000000
 ESI := 0x00000000 EDI := 0x00000000 ESP := 0x0E50FD94 EBP := 0x00080000
 CR2 := 0x00000000
```

**Comment by DisorderIy** [comment]
![burnout_progress](https://cloud.githubusercontent.com/assets/8225831/23831390/fa38e40e-0717-11e7-94cf-d8aa171fd885.png)

I've noticed that when using Intel HD 530 Graphics, I'm able to see a little more of the cars' features than what I was able to see using my AMD Radeon HD 7770, which is what I was using originally (see my first post.) This is on the latest master.

**Comment by DisorderIy** [comment]
The intro logos and title screen now display, which didn't happen before because they didn't display if you didn't have a save. The game used to black screen after the initial load screen if you had a saved game.

![crit](https://cloud.githubusercontent.com/assets/8225831/24074098/35dcf2b6-0bfa-11e7-9064-40cbe9bd9f05.png)
![title](https://cloud.githubusercontent.com/assets/8225831/24074099/35dffd76-0bfa-11e7-9aef-df27ad810185.png)

But when you press Start on the start screen, you get this message:
![unusable](https://cloud.githubusercontent.com/assets/8225831/24074115/60da8636-0bfa-11e7-8cf7-2582832bcd28.png)

**Comment by DisorderIy** [comment]
There's been a regression, and now I can't get past the first loading screen.
![burnout_crash](https://cloud.githubusercontent.com/assets/8225831/24304872/e1f08434-10b2-11e7-92c3-5793119d569c.png)

**Comment by PatrickvL** [comment]
Can you re-test this with build https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/6e250dc345f0c538238070ebf9b933dba348a114 or later?

**Comment by DisorderIy** [comment]
@PatrickvL The regression is no longer there.

**Comment by PatrickvL** [comment]
Cool! Thanks for testing. So now it's back to its initially reported behavior?

**Comment by DisorderIy** [comment]
@PatrickvL Yep!

**Comment by DisorderIy** [comment]
I'm not sure when this happened, but the issue where Burnout would fail to load the save game has been fixed. "Load Successful!" now displays before moving onto the main menu.

**Comment by PatrickvL** [comment]
I suspect this commit fixed that : https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/commit/eec43cf5ac5a59b3bb867df9afdc75351f09e6aa

**Comment by DisorderIy** [comment]
![deferred](https://cloud.githubusercontent.com/assets/8225831/25354338/850d8eb6-292a-11e7-8a61-5447cecdfdfe.png)

The game now crashes immediately with this error. I traced this back to 574d1f89cd29a0c5d64701033b8d24ff013504ad.

I hadn't been testing for a while, but I also found out that for a little while before 574d1f89cd29a0c5d64701033b8d24ff013504ad, the game crashed with a 0xC0000005.

**Comment by LukeUsher** [comment]
This has been fixed in the latest versions, it was only broken by that single commit. You can try cleaning the HLE cache manually. Settings -> Cache -> Clear

**Comment by DisorderIy** [comment]
I'm still getting that error message, though. Clearing HLE cache doesn't work.

**Comment by DisorderIy** [comment]
I'm still getting the same error on the latest build, but now I get this error after running the game right after clearing HLE cache:
![image](https://cloud.githubusercontent.com/assets/8225831/25784462/5d51de28-3365-11e7-9503-b3b45a3b7bcf.png)

Each time after that, I get the same error as before.

**Comment by UlsterRose** [comment]
As of now, there is no longer an error message box when attempting to run the game, but the game still gives a black screen. I don't know when the above issue resolved itself though.

[KrnlDebug.txt](https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/files/1187172/KrnlDebug.txt)

**Comment by BenNottelling** [comment]
@UlsterRose no error but still a black screen? Press f11 to toggle wireframe mode

**Comment by UlsterRose** [comment]
By black screen I mean Cxbx displays a black screen for about 20 seconds, then goes back to the default state with the Cxbx logo. I should've been clearer about that. F11 doesn't do anything, probably because the game doesn't seem to start now. The copy I'm using works perfectly fine on a real Xbox too, so I don't think that's the problem.

**Comment by PatrickvL** [comment]
This issue was moved to Cxbx-Reloaded/game-compatibility#197
