### ISSUE TITLE
Dual GPU laptops: improper GPU detection

### ISSUE THREAD

**Issue by ergo720** [Cxbx-Reloaded/Cxbx-Reloaded#784]
My current laptop has an integrated Intel GPU and a discrete NVIDIA GPU (Intel HD 3000 and GTX 560M). Cxbx can only detect the nvidia gpu and it's not possible to select the Intel one. On another laptop that I have, which again has an integrated intel GPU and a discrete NVIDIA GPU (Intel HD 4600 and GTX 870M), it's exactly the contrary: only the Intel one is detected and the NVIDIA one cannot be selected. I suppose this affects the emulation since NVIDIA GPUs are generally more compatible than Intel and AMD cards.

**Comment by Sarkie** [comment]
Do you have the option to do this?
https://i.stack.imgur.com/jXxmK.png

The code is here:
https://msdn.microsoft.com/en-us/library/windows/desktop/ff476877(v=vs.85).aspx

**Comment by ergo720** [comment]
Yes, I tried but it doesn't change anything. I also tried to set the option from the context menu but again it has no effect.

**Comment by RadWolfie** [comment]
Hmm... "Display Adapter" is usually base on the monitor is connected to specific display port. Supposedly you have two different graphic cards, AMD and Nvidia. If you connect one monitor to one of the AMD's card display port, then it will show AMD only on the Display Adapter. The same thing apply to Nvidia's card display port too which will show Nvidia only. This is a theory of how it works. Plus hence the name "Display" is other term of monitor.

If you do change the option base on @Sarkie's screenshot. You will have to restart the Cxbx-R in order to see the change.

**Comment by ergo720** [comment]
Yes, I restarted cxbx after every change but it seems to just disregard the setting and use whatever GPU it detects in the system.

**Comment by LukeUsher** [comment]
This is a known issue, it is caused by the fact that Cxbx-Reloaded still uses DirectX 8. 

Even if you force high performance graphics mode in GPU settings, it is ignored. 

If you use a wrapper such as dgvoodoo (not that we can't support you if you do this, it may cause issues) to act as a direct X 8-9 conversion layer, or use WineD3D, it will detect the high performance GPU just fine.

Until we move away from D3D8, it's just something we need to live with

**Comment by hrydgard** [comment]
This linker hack (place in any file, like some main.cpp or similar) fixes the issue in OpenGL applications, not sure whether it might apply to D3D8 as well:

```
// Nvidia drivers >= v302 will check if the application exports a global
// variable named NvOptimusEnablement to know if it should run the app in high
// performance graphics mode or using the IGP.
extern "C" {
	__declspec(dllexport) DWORD NvOptimusEnablement = 1;
}
```

**Comment by LukeUsher** [comment]
@hrydgard we already tried that in the past: it still doesn't fire high performance mode, because Direct3D 8 is just too old.

**Comment by PatrickvL** [comment]
Thanks tho ;)

**Comment by blueshogun96** [comment]
I can confirm on my end that Cxbx-R indeed *does* enumerate GPUs properly on my laptop.  However, when it comes to these laptops, you either need to:

A) Have that particular GPU selected as your primary display device ahead of time, or
B) Have a separate monitor and extend the displays so that you can run both GPUs at the same time.  

My laptop has an Intel HD 4000 and an NVIDIA Quadro K1000M.  Side note: I wanted to confirm that NV gives me better and less broken visuals on Smashing Drive and JSRF, and it most definitely does as previously reported.

Shogun.

**Comment by CakeLancelot** [comment]
Should be fixed now?

**Comment by LukeUsher** [comment]
Yeah, this was resolved by two ways.
1. Using D3D8to9 wrapper
2. Adding the flags for Nvidia Optimus and the equivalent AMD flag

**Comment by LukeUsher** [comment]
No longer an issue as of latest development builds that use DirectX9

**Comment by austinblesi8** [comment]
I am still having this issue with my laptop that has a i-5 8300H and a mobile GTX1050ti. I have tried forcing dedicated GPU in nvidia control panel and in windows, no avail. is this just a specific issue for my system/driver setup? I am on the CI-875f97b vs2019 build
![Capture1](https://user-images.githubusercontent.com/77245692/104133207-07e6fe00-5350-11eb-9342-3eeaee304584.PNG)
![Capture2](https://user-images.githubusercontent.com/77245692/104133208-0b7a8500-5350-11eb-920e-4d586c269d1d.PNG)

**Comment by ergo720** [comment]
Support / help request should be asked in our discord channel, not here, so locking this.
